name = "glerd"
version = "5.0.1"
description = "Generate metadata of Gleam Records for runtime reflection"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "glerd" }
gleam = ">= 1.13.0"

[javascript.deno]
allow_read = true
allow_write = true
allow_env = true
allow_run = true

[dependencies]
fswalk = ">= 3.1.0 and < 4.0.0"
glance = ">= 6.0.0 and < 7.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.67.1 and < 1.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleamyshell = ">= 2.0.2 and < 3.0.0"
glexer = ">= 2.3.0 and < 3.0.0"
gluple = ">= 2.2.0 and < 3.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
